## LU Decomposition, SVD and Applications

In [1]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt
import scipy.linalg as scl

plt.set_cmap('gray')

<Figure size 432x288 with 0 Axes>

## Resolution of linear systems through LU factorization

In [3]:
def descente(L,y):
    
    n = y.size
    x = np.zeros(n)
    
    for k in range(n):
        s=y[k];
        
        for i in range(k):
            s=s-L[k,i]*x[i]
        
        x[k]=s/L[k,k]
    return x    

In [4]:
# Test 

L = np.array([[2,0,0],[4,2,0],[6,-2,1]])

y = np.array([2,-1,1])

x1 = la.solve(L, y)
print(x1)
x2 = descente(L,y)

print(x2)

# test 
L@x2 - y

[  1.   -2.5 -10. ]
[  1.   -2.5 -10. ]


array([0., 0., 0.])

In [5]:
def montee(U,y):
    

    n=np.size(y)
    x=np.zeros(n);
    for k in range(n-1,-1,-1): 
        s=y[k];
        
        for j in range(k+1,n):
            s=s-U[k,j]*x[j]
            
        x[k]=s/U[k,k]
    return x

In [6]:
# Test 

U = np.array([[2,-1,2],[0,5,2],[0,0,2]])

y = np.array([2,-1,1])

x1 = la.solve(U, y)

print(x1)

x2 = montee(U,y)

print(x2)

[ 0.3 -0.4  0.5]
[ 0.3 -0.4  0.5]


In [7]:
def solveLU(A,b):
    
    P, L, U = scl.lu(A)
    z = P.T@b
    y = descente(L,z)
    x = montee(U,y)
    
    return x

In [8]:
A = np.array([[2,-1,1],[4,-1,4],[6,-2,8]])
b = np.array([1,-1,0])

x = solveLU(A,b)
print(x)

x1 = np.linalg.solve(A, b)
print(x1)

print('différence :', np.linalg.norm(x-x1))

[-1.00000000e+00 -3.00000000e+00  1.11022302e-16]
[-1.00000000e+00 -3.00000000e+00  1.11022302e-16]
différence : 0.0
